export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  REPORT_NOT_FOUND: "REPORT_NOT_FOUND",
  CREW_NOT_FOUND: "CREW_NOT_FOUND",
  TODO_NOT_FOUND: "TODO_NOT_FOUND",
  TICKET_NOT_WAITING: "TICKET_NOT_WAITING",
  CREW_UNAVAILABLE: "CREW_UNAVAILABLE",
  CREW_SKILL_MISMATCH: "CREW_SKILL_MISMATCH",
  CREW_HAS_OPEN_TICKET: "CREW_HAS_OPEN_TICKET",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION"
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
