export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  CREW_NOT_FOUND: "CREW_NOT_FOUND",
  TICKET_NOT_WAITING: "TICKET_NOT_WAITING",
  TICKET_NOT_ASSIGNED: "TICKET_NOT_ASSIGNED",
  CREW_OFF_DUTY: "CREW_OFF_DUTY",
  CREW_SKILL_MISMATCH: "CREW_SKILL_MISMATCH",
  CREW_HAS_OPEN_TICKET: "CREW_HAS_OPEN_TICKET"
} as const;
